name = "Yarn.Modpack.Prism"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9e47e8a3d138e34e8f7e068442ea5e100449123e8a88b243a36937e3aff313f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
