name = "Yarn.Modpack.Prism"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "627f829f70a12e599d7bc0a764c49f7ed99ed3fe7a414af91ab8c546e0688469"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
