name = "Yarn.Modpack.Prism"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c106581913d054c979550fb527f7726562aa44f2cbfb74ff1cc1686a207f8f84"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
