name = "Yarn.Modpack.Prism"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a4abcd40127a4b1f9936f90ee8726aee6adbec6f33217527892494313ddf453"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"
