#Classpaths of modded elytra layers
inject_layers = ["com.illusivesoulworks.colytra.client.ColytraLayer", "com.illusivesoulworks.elytraslot.client.ElytraSlotLayer", "com.kyanite.deeperdarker.client.render.SoulElytraRenderer"]

