name: Packwiz Update

on:
        workflow_dispatch:
        push:
                branches:
                        - build
                        - main

permissions:
  contents: write
  pull-requests: write

jobs:
  packwiz:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Refresh packwiz index
        run: packwiz refresh -y --build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          commit-message: "fix: update index"
          title: "fix: update index"
          body: "This pull request updates the index"
          branch: packwiz
          base: main
          labels: "packwiz"
          reviewers: "lilysoftpaw"